trigger:
  batch: true
  branches:
    include:
      - main
      - develop
      - issue*
  paths:
    exclude:
      - README.md

pr:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: react_app
    jobs:
      - job: install
        steps:
          - script: |
              cd app
              npm install
      - job: lint
        steps:
          - script: npm run lint:ts
      - job: build
        steps:
          - script: npm run build
