trigger:
  batch: true
  branches:
    include:
      - main
      - develop
      - issue*
  paths:
    exclude:
      - README.md

pr:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: app_dir
    value: app

stages:
  - stage: react_app
    jobs:
      - job: install
        steps:
          - script: |
              cd ${app}
              npm install
      - job: lint
        steps:
          - script: |
              cd ${app}
              npm run lint:ts
      - job: build
        steps:
          - script: |
              cd ${app}
              npm run build
