trigger:
  batch: true
  branches:
    include:
      - main
      - develop
      - issue*
  paths:
    exclude:
      - README.md

pr:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: install
    jobs:
      - job: install react app
        steps:
          - script: |
              cd app
              npm install
