trigger:
  batch: true
  branches:
    include:
      - main
      - develop
      - issue*
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: test
    displayName: test name
    jobs:
      steps:
        - script: cd app
        - script: npm install
